services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm ci && npm run build
    startCommand: php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=10000
    plan: free
